### ISSUE TITLE
Serialization error when looking up a user ID that doesn't exist

### ISSUE THREAD

**Issue by bcomnes** [HubSpot/hubspot-api-nodejs#159]
If you try to look up a contact that does not exist, the client crashes due to a serialization error because the API sends html.

```js
const results = await client.crm.contacts.basicApi.getById('notCreated@yet.com', undefined, undefined, undefined, 'email')
```

```
Error: The mediaType text/html is not supported by ObjectSerializer.parse.
    at Function.parse (/Users/bret/Developer/scratch/hubspot-tests/node_modules/@hubspot/api-client/lib/codegen/crm/contacts/models/ObjectSerializer.js:279:15)
    at BasicApiResponseProcessor.<anonymous> (/Users/bret/Developer/scratch/hubspot-tests/node_modules/@hubspot/api-client/lib/codegen/crm/contacts/apis/BasicApi.js:235:114)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/bret/Developer/scratch/hubspot-tests/node_modules/@hubspot/api-client/lib/codegen/crm/contacts/apis/BasicApi.js:5:58)
```

**Comment by ksvirkou-hubspot** [comment]
Hi
the reason on API side 
we set up `requestContext.setHeaderParam("Accept", "application/json, */*;q=0.8")` but Api returns  `text/html`

**Comment by inaiat** [comment]
Hi. The version 5.0 is ok. I tested on version 6.0.1-beta3 and got this error.

**Comment by rfrank-usgb** [comment]
Does sdk (or api) support `application/json` @ksvirkou-hubspot ?

**Comment by ksvirkou-hubspot** [comment]
Hi everyone
I ve fixed it in [the latest version](https://www.npmjs.com/package/@hubspot/api-client/v/7.0.0)
now returns `ApiException [Error]: HTTP-Code: 404`
