### ISSUE TITLE
unwrapped workflow enrollment endpoint throwing error

### ISSUE THREAD

**Issue by markl-vesper** [HubSpot/hubspot-api-nodejs#227]
Attempting to enroll a contact into a workflow and due enrollments not being wrapped in SDK yet we need to resort to instructions at

https://github.com/HubSpot/hubspot-api-nodejs#not-wrapped-endpoints

as per instructions we are calling the following

```  try {
    const apiResponse = await hubspotClient.apiRequest({
      method: 'post',
      path: `/automation/v2/workflows/${workflow.id}/enrollments/contacts/${emailAddress}`
    })
    const jsonResponse = await apiResponse.json()
    log.debug(' jsonResponse: ', jsonResponse)
    return jsonResponse
  } catch (e) {
    e.message === 'HTTP request failed'
      ? log.error('apiError: ', e.response)
      : log.error('apiError: ', e)
    return e
  }
  ```
  According to V2 documentation at https://legacydocs.hubspot.com/docs/methods/workflows/add_contact we should expect 204 response.
  
  The contact IS correctly enrolled so we know the api is working. However log.debug(' jsonResponse: ', jsonResponse) is not logged out and we see below error from catch statement. Is this normal for an endpoint that returns 204? We should be able to inspect the response for 204 yes?
  
  ```
  {
    "time": "2022-06-30T00:17:56.417Z",
    "hostname": "169.254.8.221",
    "pid": 9,
    "level": "error",
    "name": "Hubspot-lib",
    "message": "apiError:  m [FetchError]: invalid json response body at https://api.hubapi.com/automation/v2/workflows/34875036/enrollments/contacts/xxx@xxx.com?hapikey=*** reason: Unexpected end of JSON input\n    at /var/task/src/marlin/updateUserDevice.js:5:7549\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)\n    at async Object.e.exports.enrollContact (/var/task/src/marlin/updateUserDevice.js:669:5478)\n    at async Object.e.exports.updatePairing (/var/task/src/marlin/updateUserDevice.js:669:320292)\n    at async Runtime.e.exports.handle [as handler] (/var/task/src/marlin/updateUserDevice.js:669:295709) {\n  type: 'invalid-json'\n}"
}
```

**Comment by ksvirkou-hubspot** [comment]
Hi @markl-vesper 
Yes It is normal
if you get 204 response body will be empty 
you should only check the response status code
