### ISSUE TITLE
TypeError: source.on is not a function, when uploading File

### ISSUE THREAD

**Issue by Jakob-Teske** [HubSpot/hubspot-api-nodejs#401]
Hello,

I'm using the hubspot-nodejs-api in version: `9.1.1` with Node `18` and experience an error when trying to upload a file.

This is the code to upload the file:
```typescript
uploadFileToHubspot: async (uuid: string, fileBuffer: Buffer, fileName: string) => {
		return hubspotClient.files.filesApi.upload(
			{ data: fileBuffer, name: fileName},
			undefined,
			`/inquiries/${uuid}`,
			fileName,
			undefined,
			JSON.stringify({ 
				access: 'PRIVATE', overwrite: false,
				// Duplicate files will automatically be renamed
				// with "-1" or "(1)" during upload.
				duplicateValidationStrategy: 'NONE',
				duplicateValidationScope: 'ENTIRE_PORTAL',
			}),
		).then((response: any) => {
			return response;
		}).catch((error: any) => {
			console.log(error);
			return error;
		});
	},
``` 
Calling this function first results in a successfull response then this error is thrown:

```typescript
TypeError: source.on is not a function
    at Function.DelayedStream.create (/Users/xxx/Developer/company-backend/backend/node_modules/delayed-stream/lib/delayed_stream.js:33:10)
    at FormData.CombinedStream.append (/Users/xxx/Developer/company-backend/backend/node_modules/combined-stream/lib/combined_stream.js:45:37)
    at FormData.append (/Users/xxx/Developer/company-backend/backend/node_modules/@hubspot/api-client/node_modules/form-data/lib/form_data.js:74:3)
    at FilesApiRequestFactory.<anonymous> (/Users/xxx/Developer/company-backend/backend/node_modules/@hubspot/api-client/codegen/files/apis/FilesApi.ts:665:37)
    at Generator.next (<anonymous>)
    at /Users/xxx/Developer/company-backend/backend/node_modules/@hubspot/api-client/lib/codegen/files/apis/FilesApi.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/xxx/Developer/company-backend/backend/node_modules/@hubspot/api-client/lib/codegen/files/apis/FilesApi.js:4:12)
    at FilesApiRequestFactory.upload (/Users/xxx/Developer/company-backend/backend/node_modules/@hubspot/api-client/lib/codegen/files/apis/FilesApi.js:355:16)
    at ObservableFilesApi.upload (/Users/xxx/Developer/company-backend/backend/node_modules/@hubspot/api-client/codegen/files/types/ObservableAPI.ts:292:59)
    at PromiseFilesApi.upload (/Users/xxx/Developer/company-backend/backend/node_modules/@hubspot/api-client/codegen/files/types/PromiseAPI.ts:162:33)
    at /Users/xxx/Developer/company-backend/backend/src/services/hubspot.ts:261:39
    at Generator.next (<anonymous>)
    at /Users/xxx/Developer/company-backend/backend/src/services/hubspot.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/xxx/Developer/company-backend/backend/src/services/hubspot.ts:4:12)
    at Object.uploadFileToHubspot (/Users/xxx/Developer/company-backend/backend/src/services/hubspot.ts:260:84)
    at /Users/xxx/Developer/company-backend/backend/src/services/configuration.ts:50:65
    at Generator.next (<anonymous>)
    at /Users/xxx/Developer/company-backend/backend/src/services/configuration.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/xxx/Developer/company-backend/backend/src/services/configuration.ts:4:12)
    at /Users/xxx/Developer/company-backend/backend/src/services/configuration.ts:49:75
    at Array.forEach (<anonymous>)
    at /Users/xxx/Developer/company-backend/backend/src/services/configuration.ts:49:46
    at Generator.next (<anonymous>)
    at fulfilled (/Users/xxx/Developer/company-backend/backend/src/services/configuration.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
``` 

The file still get's uploaded to Hubspot, although the error is thrown.

Am I doing something wrong, or is this a bug in the SDK?

**Comment by ksvirkou-hubspot** [comment]
Hi @Jakob-Teske .
Workable example:
```javascript
async function main() {
  const hubspotClient = new hubspot.Client({ accessToken: '***' })
  const response = await hubspotClient.files.filesApi.upload(
    {
      data: fs.createReadStream('./photo.jpg'),
      name: 'photo.jpg'
    },
    undefined,
    '/folder',
    'photo.jpg',
    undefined,
    JSON.stringify({ 
      access: 'PRIVATE',
      overwrite: false,
      duplicateValidationStrategy: 'NONE',
      duplicateValidationScope: 'ENTIRE_PORTAL',
    })
  )

  console.log(response)
}
```
The SDK version is 9.1.1 .
