### ISSUE TITLE
Required parameter simplePublicObjectInput was null or undefined when calling update.

### ISSUE THREAD

**Issue by jackabe** [HubSpot/hubspot-api-nodejs#98]
Using the exact code as the API docs on which it works. But it dosn't work on my machine.

```
async function updateContact(contactId) {
  const properties = {
    company: "Biglytics",
    email: "bcooper@biglytics.net",
    firstname: "Bryan",
    lastname: "Cooper",
    phone: "(877) 929-0687",
    website: "biglytics.net",
  };
  const simplePublicObjectInput = { properties };
  const idProperty = undefined;
  console.info(contactId);

  try {
    const apiResponse = await hubspotClient.crm.contacts.basicApi.update(
      contactId,
      idProperty,
      simplePublicObjectInput
    );
    console.log(JSON.stringify(apiResponse.body, null, 2));
  } catch (e) {
    e.message === "HTTP request failed"
      ? console.error(JSON.stringify(e.response, null, 2))
      : console.error(e);
  }
}

```

This gives the following trace:

```
ERROR	Error: Required parameter simplePublicObjectInput was null or undefined when calling update.    at BasicApi.

<anonymous> (/var/task/node_modules/@hubspot/api-client/lib/codegen/crm/contacts/api/basicApi.js:438:23)    at Generator.next (<anonymous>)    at /var/task/node_modules/@hubspot/api-client/lib/codegen/crm/contacts/api/basicApi.js:19:71    at new Promise (<anonymous>)    at __awaiter (/var/task/node_modules/@hubspot/api-client/lib/codegen/crm/contacts/api/basicApi.js:15:12)    at BasicApi.update (/var/task/node_modules/@hubspot/api-client/lib/codegen/crm/contacts/api/basicApi.js:418:16)    at /var/task/node_modules/bottleneck/lib/Job.js:141:109    at Generator.next (<anonymous>)    at asyncGeneratorStep (/var/task/node_modules/bottleneck/lib/Job.js:3:103)    at _next (/var/task/node_modules/bottleneck/lib/Job.js:5:194) | 2021-08-02T13:27:28.003Z d073e86e-698d-41a7-9866-dc4cfde1f84a ERROR Error: Required parameter simplePublicObjectInput was null or undefined when calling update. at BasicApi.<anonymous> (/var/task/node_modules/@hubspot/api-client/lib/codegen/crm/contacts/api/basicApi.js:438:23) at Generator.next (<anonymous>) at /var/task/node_modules/@hubspot/api-client/lib/codegen/crm/contacts/api/basicApi.js:19:71 at new Promise (<anonymous>) at __awaiter (/var/task/node_modules/@hubspot/api-client/lib/codegen/crm/contacts/api/basicApi.js:15:12) at BasicApi.update (/var/task/node_modules/@hubspot/api-client/lib/codegen/crm/contacts/api/basicApi.js:418:16) at /var/task/node_modules/bottleneck/lib/Job.js:141:109 at Generator.next (<anonymous>) at asyncGeneratorStep (/var/task/node_modules/bottleneck/lib/Job.js:3:103) at _next (/var/task/node_modules/bottleneck/lib/Job.js:5:194)

**Comment by atanasiuk-hubspot** [comment]
Hi, @jackabe, looks like

```
const apiResponse = await hubspotClient.crm.contacts.basicApi.update(
  contactId,
  simplePublicObjectInput
);
```

would be the right call

**Comment by jackabe** [comment]
Hey @atanasiuk-hubspot if I don't include the ID parameter I get a 404.

**Comment by jackabe** [comment]
Strange I was getting a 404 when I dropped the id property parameter but it seems to work on second attempt. Thankyou.
